version: '3.8'  # Версия формата Compose

services:  # Список сервисов (контейнеров), которые мы хотим запустить

  # Сервис для Redis - идеален для кэша и активных лобби
  redis:
    image: redis:7-alpine  # Используем официальный образ Redis
    container_name: quantum-redis
    restart: unless-stopped
    ports:
      - "6379:6379"  # Пробрасываем порт на хост (localhost:6379)
    volumes:
      - redis_data:/data  # Сохраняем данные на диск (том)
    networks:
      - quantum-network

  # Сервис для MongoDB - если решим хранить историю игр и пользователей
  mongodb:
    image: mongo:6
    container_name: quantum-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - quantum-network

# Определяем тома (volumes) для постоянного хранения данных
volumes:
  redis_data:
  mongo_data:

# Определяем сеть, чтобы контейнеры видели друг друга по именам
networks:
  quantum-network:
    driver: bridge
